create table if not exists perfis (id uuid primary key references auth.users(id) on delete cascade,nome text not null,email text not null unique,criado_em timestamp default now());
create table if not exists jogos (id bigint generated by default as identity primary key,fase text not null,rodada int not null,time_a text not null,time_b text not null,estadio text,cidade text,data_jogo timestamp not null,gols_a_real int,gols_b_real int,encerrado boolean default false);
create table if not exists palpites (id bigint generated by default as identity primary key,usuario_id uuid references auth.users(id) on delete cascade,jogo_id bigint references jogos(id) on delete cascade,gols_a int not null,gols_b int not null,criado_em timestamp default now(),unique(usuario_id,jogo_id));
alter table perfis enable row level security;alter table jogos enable row level security;alter table palpites enable row level security;
create policy "perfis_select_todos" on perfis for select to authenticated using (true);
create policy "perfis_insert_proprio" on perfis for insert to authenticated with check (auth.uid() = id);
create policy "perfis_update_proprio" on perfis for update to authenticated using (auth.uid() = id);
create policy "jogos_select_todos" on jogos for select to authenticated using (true);
create policy "jogos_update_admin_livre" on jogos for update to authenticated using (true) with check (true);
create policy "palpites_select_todos" on palpites for select to authenticated using (true);
create policy "palpites_insert_proprio" on palpites for insert to authenticated with check (auth.uid() = usuario_id);
create policy "palpites_update_proprio" on palpites for update to authenticated using (auth.uid() = usuario_id) with check (auth.uid() = usuario_id);
insert into jogos (fase,rodada,time_a,time_b,estadio,cidade,data_jogo) values
('Fase de Grupos',1,'Brasil','Marrocos','MetLife Stadium','Nova York / Nova Jersey','2026-06-13 19:00:00'),
('Fase de Grupos',2,'Brasil','Haiti','Lincoln Financial Field','Filadélfia','2026-06-19 21:30:00'),
('Fase de Grupos',3,'Escócia','Brasil','Hard Rock Stadium','Miami','2026-06-24 19:00:00');